version: '3.8'

services:
  # MySQL Database
  mysql:
    image: mysql:8.0
    container_name: mysql_1
    networks:
      - yoyo_network
    volumes:
      - ./db/conf.d:/etc/mysql/conf.d
      - ./db/data:/var/lib/mysql
      - ./db/initdb.d:/docker-entrypoint-initdb.d
    env_file: .env
    ports:
      - "3306:3306"
    environment:
      - TZ=Asia/Seoul
      - MYSQL_ROOT_PASSWORD=rootpassword
      - MYSQL_USER=ssafy
      - MYSQL_PASSWORD=ssafy
      - MYSQL_DATABASE=yoyo
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h 127.0.0.1 -u${MYSQL_USER} --password=${MYSQL_PASSWORD}"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Redis Cache
  redis:
    image: redis:alpine
    restart: always
    container_name: redis_boot
    command: redis-server --port 6379
    hostname: redis
    ports:
      - "6379:6379"

  # Config Server
  config-server:
    image: config-server:1.0.0
    container_name: config-server
    build:
      context: ./config-server
    ports:
      - "8888:8888"
    networks:
      - yoyo_network
    environment:
      - SPRING_PROFILES_ACTIVE=default
    healthcheck:
      test: [ "CMD-SHELL", "curl -f http://localhost:8888/actuator/health || exit 1" ]
      interval: 10s
      timeout: 5s
      retries: 5

  # Eureka Server
  eureka-server:
    image: eureka-server:1.0.0
    container_name: eureka_1
    build:
      context: ./eureka-server
    ports:
      - "8761:8761"
    networks:
      - yoyo_network
    depends_on:
      - config-server
    environment:
      - SPRING_PROFILES_ACTIVE=default
      - EUREKA_CLIENT_REGISTER_WITH_EUREKA=false
      - EUREKA_CLIENT_FETCH_REGISTRY=false
      - SPRING_CLOUD_CONFIG_URI=http://config-server:8888
      - SPRING_CLOUD_CONFIG_NAME=eureka
      - SPRING_PROFILES_ACTIVE=dev

  # Member Service
  member-service:
    image: member-service:1.0.0
    container_name: member-service
    build:
      context: ./member-service
    networks:
      - yoyo_network
    ports:
      - "8081:8081"
    depends_on:
      - mysql
      - redis
      - eureka-server
      - config-server
    environment:
      - SPRING_PROFILES_ACTIVE=default
      - SPRING_CLOUD_CONFIG_URI=http://config-server:8888
      - SPRING_CLOUD_CONFIG_NAME=member
      - SPRING_PROFILES_ACTIVE=dev

  # Banking Service
  banking-service:
    image: banking-service:1.0.0
    container_name: banking-service
    build:
      context: ./banking-service
    networks:
      - yoyo_network
    ports:
      - "8082:8082"
    depends_on:
      - mysql
      - eureka-server
      - config-server
    environment:
      - SPRING_CLOUD_CONFIG_URI=http://config-server:8888
      - SPRING_CLOUD_CONFIG_NAME=banking
      - SPRING_PROFILES_ACTIVE=dev

  # Transaction Service
  transaction-service:
    image: transaction-service:1.0.0
    container_name: transaction-service
    build:
      context: ./transaction-service
    networks:
      - yoyo_network
    ports:
      - "8083:8083"
    depends_on:
      - mysql
      - eureka-server
      - config-server
    environment:
      - SPRING_CLOUD_CONFIG_URI=http://config-server:8888
      - SPRING_CLOUD_CONFIG_NAME=transaction
      - SPRING_PROFILES_ACTIVE=dev


  # Notification Service
  notification-service:
    image: notification-service:1.0.0
    container_name: notification-service
    build:
      context: ./notification-service
    networks:
      - yoyo_network
    ports:
      - "8084:8084"
    depends_on:
      - mysql
      - eureka-server
      - config-server
    environment:
      - SPRING_CLOUD_CONFIG_URI=http://config-server:8888
      - SPRING_CLOUD_CONFIG_NAME=notification
      - SPRING_PROFILES_ACTIVE=dev

  # Payment Service
  payment-service:
    image: payment-service:1.0.0
    container_name: payment-service
    build:
      context: ./payment-service
    networks:
      - yoyo_network
    ports:
      - "8085:8085"
    depends_on:
      - mysql
      - eureka-server
      - config-server
    environment:
      - SPRING_CLOUD_CONFIG_URI=http://config-server:8888
      - SPRING_CLOUD_CONFIG_NAME=payment
      - SPRING_PROFILES_ACTIVE=dev

  # Event Service
  event-service:
    image: event-service:1.0.0
    container_name: event-service
    build:
      context: ./event-service
    networks:
      - yoyo_network
    ports:
      - "8086:8086"
    depends_on:
      - mysql
      - eureka-server
      - config-server
    environment:
      - SPRING_CLOUD_CONFIG_URI=http://config-server:8888
      - SPRING_CLOUD_CONFIG_NAME=event
      - SPRING_PROFILES_ACTIVE=dev

  # Spring Cloud Gateway
  scg:
    image: scg:1.0.0
    container_name: spring-cloud-gateway
    build:
      context: ./scg
    networks:
      - yoyo_network
    ports:
      - "8080:8080"
    depends_on:
      - eureka-server
    environment:
      - SPRING_CLOUD_CONFIG_URI=http://config-server:8888
      - SPRING_CLOUD_CONFIG_NAME=scg
      - SPRING_PROFILES_ACTIVE=dev

  # Zookeeper for Kafka
  zookeeper:
    image: bitnami/zookeeper:3.8.0
    container_name: zookeeper
    networks:
      - yoyo_network
    ports:
      - '2181:2181'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
      - ZOO_TLS_CLIENT_AUTH=none
      - ZOO_TLS_QUORUM_CLIENT_AUTH=none

  # Kafka for event-driven communication
  kafka:
    image: 'bitnami/kafka:latest'
    container_name: kafka
    networks:
      - yoyo_network
    ports:
      - '9092:9092'
    depends_on:
      - zookeeper
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CLIENT:PLAINTEXT,EXTERNAL:PLAINTEXT
      - KAFKA_CFG_LISTENERS=CLIENT://:9092,EXTERNAL://:9093
      - KAFKA_CFG_ADVERTISED_LISTENERS=CLIENT://kafka:9092,EXTERNAL://localhost:9093
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=CLIENT

networks:
 yoyo_network:
   driver: bridge