version : '3'
services:
  mysql:
    image: mysql:8.0
    networks:
      - yoyo_network
    volumes:
      - ./db/conf.d:/etc/mysql/conf.d
      - ./db/data:/var/lib/mysql
      - ./db/initdb.d:/docker-entrypoint-initdb.d
    env_file: .env
    ports:
      - "3306:3306"
    environment:
      - TZ=Asia/Seoul
      - MYSQL_ROOT_PASSWORD=rootpassword
      - MYSQL_USER=ssafy
      - MYSQL_PASSWORD=ssafy
      - MYSQL_DATABASE=yoyo
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:alpine
    restart: always
    container_name: redis_boot
    command: redis-server --port 6379
    hostname: redis
    ports:
      - "6379:6379"

#  common:
#    image: yoyo-common:1.0.0
#    networks:
#      - yoyo_network
#    ports:
#      - "8088:8080"
#    depends_on:
#      - mysql
#    environment:
#      - KAFKA_CLUSTERS_BOOTSTRAPSERVERS=kafka:29092
#      - LOGGING_TOPIC=yoyo.logging.out.stdout

  eureka-service:
    image: yoyo-eureka-server:1.0.0
    networks:
      - yoyo_network
    ports:
      - "8761:8761"
    environment:
      - SERVER_PORT=8761
      - EUREKA_CLIENT_REGISTER_WITH_EUREKA=false
      - EUREKA_CLIENT_FETCH_REGISTRY=false

  member-service:
    image: yoyo-member-service:1.0.0
    networks:
      - yoyo_network
    ports:
      - "8081:8081"
    depends_on:
      - mysql
      - redis
      - eureka-service
    env_file: .env
    environment:
      - SERVER_PORT=8081
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/yoyo
      - SPRING_DATASOURCE_USERNAME=ssafy
      - SPRING_DATASOURCE_PASSWORD=ssafy
      - SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT=org.hibernate.dialect.MySQL8Dialect
      - SPRING_JPA_HIBERNATE_DDL_AUTO=create
      - KAFKA_CLUSTERS_BOOTSTRAPSERVERS=kafka:29092
      - LOGGING_TOPIC=yoyo.logging.out.stdout
      - SPRING_PROFILES_ACTIVE=local
      - JWT_SECRET=NYd4nEtyLtcU7cpS/1HTFVmQJd7MmrP+HafWoXZjWNOL7qKccOOUfQNEx5yvG6dfdpuBeyMs9eEbRmdBrPQCNg==
      - JWT_EXPIRATION_MS=20000
      - JWT_REFRESH_EXPIRATION_MS=60000
      - SPRING_APPLICATION_NAME=member-service
      - EUREKA_CLIENT_REGISTER_WITH_EUREKA=true
      - EUREKA_CLIENT_FETCH_REGISTRY=true
      - EUREKA_SERVICEURL_DEFAULTZONE=http://admin:1234@localhost:8761/eureka



  banking-service:
    image: yoyo-banking-service:1.0.0
    networks:
      - yoyo_network
    ports:
      - "8082:8082"
    depends_on:
      - mysql
      - eureka-service
    environment:
      - SERVER_PORT=8082
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/yoyo
      - SPRING_DATASOURCE_USERNAME=ssafy
      - SPRING_DATASOURCE_PASSWORD=ssafy
      - SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT=org.hibernate.dialect.MySQL8Dialect
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - KAFKA_CLUSTERS_BOOTSTRAPSERVERS=kafka:29092
      - LOGGING_TOPIC=yoyo.logging.out.stdout
      - SPRING_APPLICATION_NAME=banking-service
      - EUREKA_CLIENT_REGISTER_WITH_EUREKA=true
      - EUREKA_CLIENT_FETCH_REGISTRY=true
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://admin:1234@localhost:8761/eureka
      - TZ=Asia/Seoul

  transaction-service:
    image: yoyo-transaction-service:1.0.0
    networks:
      - yoyo_network
    ports:
      - "8083:8083"
    depends_on:
      - mysql
      - eureka-service
    environment:
      - SERVER_PORT=8083
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/yoyo
      - SPRING_DATASOURCE_USERNAME=ssafy
      - SPRING_DATASOURCE_PASSWORD=ssafy
      - SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT=org.hibernate.dialect.MySQL8Dialect
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - KAFKA_CLUSTERS_BOOTSTRAPSERVERS=kafka:29092
      - LOGGING_TOPIC=yoyo.logging.out.stdout
      - SPRING_APPLICATION_NAME=transaction-service
      - EUREKA_CLIENT_REGISTER_WITH_EUREKA=true
      - EUREKA_CLIENT_FETCH_REGISTRY=true
      - EUREKA_SERVICEURL_DEFAULTZONE=http://admin:1234@localhost:8761/eureka

  notification-service:
    image: yoyo-notification-service:1.0.0
    networks:
      - yoyo_network
    ports:
      - "8084:8084"
    depends_on:
      - mysql
      - eureka-service
    environment:
      - SERVER_PORT=8084
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/yoyo
      - SPRING_DATASOURCE_USERNAME=ssafy
      - SPRING_DATASOURCE_PASSWORD=ssafy
      - SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT=org.hibernate.dialect.MySQL8Dialect
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - KAFKA_CLUSTERS_BOOTSTRAPSERVERS=kafka:29092
      - LOGGING_TOPIC=yoyo.logging.out.stdout
      - SPRING_APPLICATION_NAME=notification-service
      - EUREKA_CLIENT_REGISTER_WITH_EUREKA=true
      - EUREKA_CLIENT_FETCH_REGISTRY=true
      - EUREKA_SERVICEURL_DEFAULTZONE=http://admin:1234@localhost:8761/eureka

  payment-service:
    image: yoyo-payment-service:1.0.0
    networks:
      - yoyo_network
    ports:
      - "8085:8085"
    depends_on:
      - mysql
      - eureka-service
    environment:
      - SERVER_PORT=8085
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/yoyo
      - SPRING_DATASOURCE_USERNAME=ssafy
      - SPRING_DATASOURCE_PASSWORD=ssafy
      - SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT=org.hibernate.dialect.MySQL8Dialect
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - KAFKA_CLUSTERS_BOOTSTRAPSERVERS=kafka:29092
      - LOGGING_TOPIC=yoyo.logging.out.stdout
      - SPRING_DEVTOOLS_LIVERELOAD_ENABLED=true
      - SPRING_FREEMARKER_CACHE=false
      - SPRING_THYMELEAF_CACHE=false
      - LOGGING_LEVEL_ROOT=info
      - PAYMENT_SECRET=test_sk_zXLkKEypNArWmo50nX3lmeaxYG5R
      - PAYMENT_URL=https://api.tosspayments.com/v1/payments/confirm
      - SPRING_APPLICATION_NAME=payment-service
      - EUREKA_CLIENT_REGISTER_WITH_EUREKA=true
      - EUREKA_CLIENT_FETCH_REGISTRY=true
      - EUREKA_SERVICEURL_DEFAULTZONE=http://admin:1234@localhost:8761/eureka

  event-service:
    image: yoyo-event-service:1.0.0
    networks:
      - yoyo_network
    ports:
      - "8086:8086"
    depends_on:
      - mysql
      - eureka-service
    environment:
      - SERVER_PORT=8086
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/yoyo
      - SPRING_DATASOURCE_USERNAME=ssafy
      - SPRING_DATASOURCE_PASSWORD=ssafy
      - SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT=org.hibernate.dialect.MySQL8Dialect
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - KAFKA_CLUSTERS_BOOTSTRAPSERVERS=kafka:29092
      - LOGGING_TOPIC=yoyo.logging.out.stdout
      - SPRING_APPLICATION_NAME=event-service
      - EUREKA_CLIENT_REGISTER_WITH_EUREKA=true
      - EUREKA_CLIENT_FETCH_REGISTRY=true
      - EUREKA_SERVICEURL_DEFAULTZONE=http://admin:1234@localhost:8761/eureka

  zookeeper:
    image: bitnami/zookeeper:3.8.0
    networks:
      - yoyo_network
    ports:
      - '2181:2181'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
      - ZOO_TLS_CLIENT_AUTH=none
      - ZOO_TLS_QUORUM_CLIENT_AUTH=none

  kafka:
    image: 'bitnami/kafka:3.4.0'
    networks:
      - yoyo_network
    ports:
      - '9092:9092'
      - '29092:29092'
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_LISTENERS=PLAINTEXT://kafka:29092,EXTERNAL://0.0.0.0:9092  # 내부 통신용 및 외부 통신용 리스너
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:29092,EXTERNAL://localhost:9092  # 외부 클라이언트 접근시 localhost:9092 사용
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT,EXTERNAL:PLAINTEXT
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=PLAINTEXT  # 브로커 간 통신에 사용하는 리스너 명칭
    depends_on:
      - zookeeper

#  kafka-ui:
#    image: provectuslabs/kafka-ui
#    container_name: kafka-ui
#    networks:
#      - yoyo_network
#    ports:
#      - "8989:8080"
#    restart: always
#    depends_on:
#      - kafka
#      - zookeeper
#    environment:
#      - KAFKA_CLUSTERS_0_NAME=local
#      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=localhost:9092
#      - KAFKA_CLUSTERS_0_ZOOKEEPER=zookeeper:2181

networks:
  yoyo_network:
    driver: bridge