version: '3.8'

services:
  # MySQL Database
  mysql:
    image: mysql:8.0
    container_name: mysql_1
    networks:
      - yoyo_network
    volumes:
      - ./db/conf.d:/etc/mysql/conf.d
      - ./db/data:/var/lib/mysql
      - ./db/initdb.d:/docker-entrypoint-initdb.d
    env_file: .env
    ports:
      - "3306:3306"
    environment:
      - TZ=Asia/Seoul
      - MYSQL_ROOT_PASSWORD=rootpassword
      - MYSQL_USER=ssafy
      - MYSQL_PASSWORD=ssafy
      - MYSQL_DATABASE=yoyo
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Redis Cache
  redis:
    image: redis:alpine
    restart: always
    container_name: redis_boot
    command: redis-server --port 6379
    hostname: redis
    ports:
      - "6379:6379"

  # Config Server
  config-server:
    image: config-server:1.0.0
    build:
      context: ./config-server
    ports:
      - "8888:8888"
    networks:
      - yoyo_network
    environment:
      - SPRING_PROFILES_ACTIVE=default

  # Eureka Server
  eureka-service:
    image: eureka-server:1.0.0
    container_name: eureka_1
    build:
      context: ./eureka-server
    ports:
      - "8761:8761"
    networks:
      - yoyo_network
    depends_on:
      - config-server
    environment:
      - SPRING_PROFILES_ACTIVE=default
      - EUREKA_CLIENT_REGISTER_WITH_EUREKA=false
      - EUREKA_CLIENT_FETCH_REGISTRY=false
      - SPRING_CLOUD_CONFIG_URI=http://config-server:8888
      - SPRING_CLOUD_CONFIG_NAME=eureka
      - SPRING_PROFILES_ACTIVE=dev

  # Member Service
  member-service:
    image: member-service:1.0.0
    build:
      context: ./member-service
    networks:
      - yoyo_network
    ports:
      - "8081:8081"
    depends_on:
      - mysql
      - redis
      - eureka-service
    environment:
      - SPRING_PROFILES_ACTIVE=default
      - SPRING_CLOUD_CONFIG_URI=http://config-server:8888
      - SPRING_CLOUD_CONFIG_NAME=member
      - SPRING_PROFILES_ACTIVE=dev

  # Banking Service
  banking-service:
    image: banking-service:1.0.0
    build:
      context: ./banking-service
    networks:
      - yoyo_network
    ports:
      - "8082:8082"
    depends_on:
      - mysql
      - eureka-service
    environment:
      - SPRING_CLOUD_CONFIG_URI=http://config-server:8888
      - SPRING_CLOUD_CONFIG_NAME=banking
      - SPRING_PROFILES_ACTIVE=dev

  # Transaction Service
  transaction-service:
    image: transaction-service:1.0.0
    build:
      context: ./transaction-service
    networks:
      - yoyo_network
    ports:
      - "8083:8083"
    depends_on:
      - mysql
      - eureka-service
    environment:
      - SPRING_CLOUD_CONFIG_URI=http://config-server:8888
      - SPRING_CLOUD_CONFIG_NAME=transaction
      - SPRING_PROFILES_ACTIVE=dev


  # Notification Service
  notification-service:
    image: notification-service:1.0.0
    build:
      context: ./notification-service
    networks:
      - yoyo_network
    ports:
      - "8084:8084"
    depends_on:
      - mysql
      - eureka-service
    environment:
      - SPRING_CLOUD_CONFIG_URI=http://config-server:8888
      - SPRING_CLOUD_CONFIG_NAME=notification
      - SPRING_PROFILES_ACTIVE=dev

  # Payment Service
  payment-service:
    image: payment-service:1.0.0
    build:
      context: ./payment-service
    networks:
      - yoyo_network
    ports:
      - "8085:8085"
    depends_on:
      - mysql
      - eureka-service
    environment:
      - SPRING_CLOUD_CONFIG_URI=http://config-server:8888
      - SPRING_CLOUD_CONFIG_NAME=payment
      - SPRING_PROFILES_ACTIVE=dev

  # Event Service
  event-service:
    image: event-service:1.0.0
    build:
      context: ./event-service
    networks:
      - yoyo_network
    ports:
      - "8086:8086"
    depends_on:
      - mysql
      - eureka-service
    environment:
      - SPRING_CLOUD_CONFIG_URI=http://config-server:8888
      - SPRING_CLOUD_CONFIG_NAME=event
      - SPRING_PROFILES_ACTIVE=dev

  # Spring Cloud Gateway
  scg:
    image: scg:1.0.0
    build:
      context: ./scg
    networks:
      - yoyo_network
    ports:
      - "8080:8080"
    depends_on:
      - eureka-service
    environment:
      - SPRING_CLOUD_CONFIG_URI=http://config-server:8888
      - SPRING_CLOUD_CONFIG_NAME=scg
      - SPRING_PROFILES_ACTIVE=dev

  # Zookeeper for Kafka
  zookeeper:
    image: bitnami/zookeeper:3.8.0
    networks:
      - yoyo_network
    ports:
      - '2181:2181'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
      - ZOO_TLS_CLIENT_AUTH=none
      - ZOO_TLS_QUORUM_CLIENT_AUTH=none

  # Kafka for event-driven communication
  kafka:
    image: 'bitnami/kafka:3.4.0'
    networks:
      - yoyo_network
    ports:
      - '9092:9092'
    depends_on:
      - zookeeper
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_CFG_LISTENERS=PLAINTEXT://kafka:9092
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://localhost:9092

networks:
 yoyo_network:
   driver: bridge