spring:
  redis:
    host: localhost
    port: 6379
  profiles:
    active: local
    include: local
cool-sms:
  api-key: ${coolsms.key}
  api-secret: ${coolsms.secret}
  domain: ${coolsms.domain}
  send-phone-number: ${coolsms.sendNumber}