spring:
  profiles:
    active: local
    include: local
  application:
    name: yoyo
  redis:
    host: localhost
    port: 6379
server:
  port: 8080

cool-sms:
  api-key: ${coolsms.key}
  api-secret: ${coolsms.secret}
  domain: ${coolsms.domain}
  send-phone-number: ${coolsms.sendNumber}