spring:
  profiles:
    active: local
    include: local
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: ${git.config.repository}
#          ignore-local-ssh-settings: true
#          private-key: ${git.private}
          username: ${git.username}
          password: ${git.password}

server:
  port: 8888
#  1. application.yaml
#  2. application.yaml
#  3. application-{profile}.yaml
#  4. {application name}/{application name}-{profile}